AUGMENTATION: true
BATCH_SIZE: 16
CLASSES: 6
EPOCHS: 10
FREEZE_TILL_REMAIN_LAYERS: 4
IMAGE_SIZE:
- 80
- 80
- 3
INCLUDE_TOP: false
LEARNING_RATE: 1.0e-05
TRAIN_VAL_TEST_RATIO:
- 0.8
- 0.1
- 0.1
WEIGHTS: imagenet
