artifacts_root: artifacts
data_ingestion:
  dataset_dir: artifacts/data_ingestion/dataset
  is_googledriver: false
  local_data_file: artifacts/data_ingestion/data.zip
  root_dir: artifacts/data_ingestion
  source_URL: DatasetPath\Dataset_TGV_250301_6classes.zip
  unzip_dir: artifacts/data_ingestion
evaluation:
  remote_log: false
  repository_name: TGV-Dataset-Classification
  repository_owner: duyloca1
prepare_base_model:
  base_model_path: artifacts/prepare_base_model/base_model.h5
  root_dir: artifacts/prepare_base_model
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5
training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5
